apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: activemq
  description: Test activeMQ
  annotations:
    github.com/project-slug: crlsquilumba/activemq
spec:
  type: website
  lifecycle: experimental
  owner: user:default/guest
  domain: investigacion-ia
  system: Solucion MQ
